### PR TITLE
Ebere

### PR DESCRIPTION
**Pull request by ebereanuebunwa**
I set up the Custom UserModel and registered it in the settings.py file.
You may check the comments I left on each commit.

I also set up one-to-one relationships between the two user models, and the customusermodel.
With this, we may not need to define the email and password fields in the school and student model again.
But now we can define (is_student = True) inside the student model and (is_school = True) inside the school model.

### CODE REVIEW

**Review by collinsezedike — CHANGES_REQUESTED** [review]
Nice work, Chief!
Will the forms not be created from the front end?

**Comment by ebereanuebunwa** [comment]
The will bro, this is just for the admin panel.

**Comment by collinsezedike** [comment]
`localhost:8000/admin` or `school-dashboard/admin`

**Comment by ebereanuebunwa** [comment]
localhost/admin

**Pull request merged**
